language: node_js
node_js: "10.6.0"
services:
  - postgresql
env:
  global:
    - CC_TEST_REPORTER_ID=78bee3f9ed43299d5018856babca7f2de83d157ed6eca244ff6c9d5327722e5a
before_script:
  - psql -c 'CREATE DATABASE travis_ci;' -U postgres
  - psql -c 'CREATE TABLE users (id serial PRIMARY KEY, firstname varchar(100) not null, lastname varchar(100) not null, email varchar(100) not null, password varchar(250) not null, created_at TIMESTAMP NOT NULL DEFAULT NOW(), updated_at TIMESTAMP NOT NULL DEFAULT NOW());' -U postgres -d travis_ci
  - psql -c "INSERT INTO users (firstname, lastname, email, password) VALUES ('sullivan', 'wisdom', 'sullivan@gmail.com' ,'lastdays');" -U postgres -d travis_ci
  - psql -c 'CREATE TABLE entries (id serial PRIMARY KEY, title varchar(100) not null, image_url varchar(1000) not null, note TEXT not null, user_id integer REFERENCES users (id), created_at TIMESTAMP NOT NULL DEFAULT NOW(), updated_at TIMESTAMP NOT NULL DEFAULT NOW());' -U postgres -d travis_ci
  - psql -c 'INSERT INTO entries (title, image_url, note) VALUES('The life of Pablo', 'https://travis-ci.org/wiztemple/Diarium/settings', 'A song released in 1958 by Bill Mack, an American songwriter-country artist and country radio disc jockey. It has since been covered by several artists, in particular by country singer LeAnn Rimes');" -U postgres -d travis_ci
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
cache: 
  directories:
    - 'node_modules'
    
script:
  - npm test

after_script:
  - npm run coverage
  - npm run coveralls
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  after_success:
  - npm run coverage